description: Action ressource.
get:
  is: [auth: {roles: 'none'} ]
  description: Retrieve a list of all the Actions
  responses:
    200:
      body:
        application/json:
          example: |
            [
              {
                "commentId": "7",
                "author": "tony2017",
                "type": "Create a new comment",
                "date": "2015.02.15",
                "content": "le lampadaire à disparu lol !",
                "issueId": "123"
              },
              {
                "author": "tony2017",
                "type": "Change the issue status",
                "date": "2015.02.15",
                "content": "resolved",
                "issueId": "123"
              },
              {
                "author": "tony2017",
                "type": "Change the issue responsable",
                "date": "2015.02.15",
                "content": "LL92",
                "issueId": "123"
              }   
            ]
    404:
      body:
        application/json:
          example: |
            {"message": "Actions not found"}
/comments:
  post:
    is: [auth: {roles: 'any'} ]
    description: Create a new comment.
    body:
      application/json:
        example: |
          {
            "author": "tony2017",
            "content": "le lampadaire à disparu lol !",
            "issueId": "123"
          }
    responses:
      201:
        body:
          application/json:
            example: |
              {
                "commentId": "7",
                "author": "tony2017",
                "type": "Create a new comment",
                "date": "2015.02.15",
                "content": "le lampadaire à disparu lol !",
                "issueId": "123"
              }
  /{issueId}:
    put:
      is: [auth: {roles: 'any'} ]
      description: Update a comment specified by its id
      body:
        application/json:
          example: |
            {
              "commentId": "7",
              "author": "tony2017",
              "date": "2015.02.25",
              "content": "le lampadaire est à nouveau fonctionnel, c'était rapide",
              "issueId": "123"
            }
      responses:
        200:
          body:
            application/json:
              example: |
                {
                  "commentId": "7",
                  "author": "tony2017",
                  "type": "Modify an existing comment",
                  "date": "2015.02.25",
                  "content": "le lampadaire est à nouveau fonctionnel, c'était rapide",
                  "issueId": "123"
                }
    delete:
      is: [auth: {roles: 'any'} ]
      description: Delete a specific comment.
      body:
        application/json:
          example: |
            {
              "commentId": "7",
              "author": "tony2017",
              "type": "Remove an existing comment",
              "issueId": "123"
            }
      responses:
        204:
          body:
/statut:
  /{issueId}:
    put:
      is: [auth: {roles: 'staff'} ]
      description: Update an status related to an issue by its id
      body:
        application/json:
          example: |
            {
              "author": "tony2017",
              "content": "resolved",
              "issueId": "123"
            }
      responses:
        200:
          body:
            application/json:
              example: |
                {
                  "author": "tony2017",
                  "type": "Change the issue status",
                  "date": "2015.02.15",
                  "content": "resolved",
                  "issueId": "123"
                }
/responsable:
  /{issueId}:
    put:
      is: [auth: {roles: 'staff'} ]
      description: Update an responsable related to an issue by its id
      body:
        application/json:
          example: |
            {
              "author": "tony2017",
              "content": "LL92",
              "issueId": "123"
            }
      responses:
        200:
          body:
            application/json:
              example: |
                {
                  "author": "tony2017",
                  "type": "Change the issue responsable",
                  "date": "2015.02.15",
                  "content": "LL92",
                  "issueId": "123"
                }