#%RAML 0.8
---
title: API Resource
baseUri: https://localhost/api/
protocols: [HTTPS]
mediaType: application/json

traits:
  - auth: !include _traits/auth.raml

/users: !include users.raml

/data: !include data.raml

/issue: !include issue.raml

/issueType: !include issueType.raml

/action: !include action.raml