#%RAML 0.8
---
title: API Resource
baseUri: https://localhost/api/
protocols: [HTTPS]
mediaType: application/json

traits:
  - auth: !include _traits/auth.raml

/users: !include users.raml

/issues: !include issues.raml

/issuesType: !include issuesType.raml

/actions: !include actions.raml