description: Issue resource.
get:
  is: [auth: {roles: 'none'} ]
  description: Retrieve a list of issues
  queryParameters:
    author:
      type: string
      description: An author's full name
      example: LL92
      required: true
    responsable:
      type: string
      description: A responsable's full name
      example: staff_member_one
      required: false
    issueType:
      type: string
      description: An issue's type
      example: broken streetlight
      required: true
    status:
      type: string
      description: An issue's status
      example: pending
      required: true
    latitude:
      type: number
      description: An issue's latitude
      example: 46.7833
      required: true
    longitude:
      type: number
      description: An issue's longitude
      example: 6.65
      required: true
    createdOn:
      type: date
      description: the date of the issue's creation
      example: 2015/02/15
      required: false
    updateOn:
      type: date
      description: The date of the last update
      example: 2015/02/25
      required: false
  responses:
    200:
      body:
        application/json:
          example: |
            [
              {
                "id": "123",
                "author": "LL92",
                "responsable": "staff_member_one",
                "issueType": "broken streetlight",
                "description": "Lampadaire mort",
                "tags":  ["lampadaire","ampoule"],
                "status" : "created",
                "latitude": "46.7833",
                "longitude": "6.65",
                "createdOn": "2015/02/15",
                "updateOn" : "2015/02/25",
                "comment" : 
                  [
                    {
                      "author" : "Tony2017",
                      "date" : "2015.02.15",
                      "content":"le lampadaire à disparu lol !"
                    },
                    {
                      "author" : "LL92",
                      "date" : "2015.02.15",
                      "content":"YOLO la lampe"
                    }
                  ]
              },
              
              ...
              
            ]
    404:
      body:
        application/json:
          example: |
            {"message": "Issue not found"}
post:
  is: [auth: {roles: 'any'} ]
  description: Create a new issue.
  body:
    application/json:
      example: |
        {
          "author": "LL92",
          "responsable": "staff_member_one",
          "issueType": "broken streetlight",
          "description": "Lampadaire mort",
          "tags":  ["lampadaire","ampoule"],
          "latitude": "46.7833",
          "longitude": "6.65"
        }
  responses:
    201:
      body:
        application/json:
          example: |
            {
              "id": "123",
              "author": "LL92",
              "responsable": "staff_member_one",
              "issueType": "broken streetlight",
              "description": "Lampadaire mort",
              "tags":  ["lampadaire","ampoule"],
              "status" : "created",
              "latitude": "46.7833",
              "longitude": "6.65",
              "createdOn": "2015/02/15"
            }

/{issueId}:
  get:
    is: [auth: {roles: 'any'} ]
    description: Retrieve an issue specified by its id
    queryParameters:
      id:
        type: number
        description: the issue id
        example: 123
        required: true
    responses:
      200:
        body:
          application/json:
            example: |
              {
                "id": "123",
                "author": "LL92",
                "responsable": "staff_member_one",
                "issueType": "broken streetlight",
                "description": "Lampadaire mort",
                "tags":  ["lampadaire","ampoule"],
                "status" : "created",
                "latitude": "46.7833",
                "longitude": "6.65",
                "createdOn": "2015/02/15",
                "updateOn" : "2015/02/25",
                "comment" : 
                  [
                    {
                      "author" : "Tony2017",
                      "date" : "2015.02.15",
                      "content":"le lampadaire à disparu lol !"
                    },
                    {
                      "author" : "LL92",
                      "date" : "2015.02.15",
                      "content":"YOLO la lampe"
                    }
                  ]
              }
      404:
        body:
          application/json:
            example: |
              {"message": "Issue not found"}
  put:
    is: [auth: {roles: 'any'} ]
    description: Update an issue specified by its id
    body:
      application/json:
        example: |
          {
            "id": "123",
            "author": "LL92",
            "responsable": "staff_member_one",
            "issueType": "broken streetlight",
            "description": "Lampadaire mort",
            "tags":  ["lampadaire","ampoule"],
            "status" : "resolved",
            "latitude": "46.7833",
            "longitude": "6.65",
            "createdOn": "2015/02/15",
            "updateOn" : "2015/02/25"
          }
    responses:
      201:
        body:
          application/json:
            example: |
              {
                "id": "123",
                "author": "LL92",
                "responsable": "staff_member_one",
                "issueType": "broken streetlight",
                "description": "Lampadaire mort",
                "tags":  ["lampadaire","ampoule"],
                "status" : "resolved",
                "latitude": "46.7833",
                "longitude": "6.65",
                "createdOn": "2015/02/15",
                "updateOn" : "2015/02/25"
              }
  /tags:
    post:
      description: Create a new tag
      body:
        application/json:
          example: |
            {
              "keyword": "tag"
            }
      responses:
        201:
          body:
            application/json:
              example: |
                {
                  "id": "123",
                  "author": "LL92",
                  "responsable": "staff_member_one",
                  "issueType": "broken streetlight",
                  "description": "Lampadaire mort",
                  "tags":  
                    [
                      {
                        "id": "abc",
                        "keyword": "¨tag"
                      }
                    ],
                  "status" : "resolved",
                  "latitude": "46.7833",
                  "longitude": "6.65",
                  "createdOn": "2015/02/15",
                  "updateOn" : "2015/02/25"
                }
    put:
      description: Update a tag based on a issueId
      body:
        application/json:
          example: |
            {
              "tagId": "abc",
              "keyword": "new tag"
            }
      responses:
        201:
          body:
            application/json:
              example: |
                {
                  "id": "123",
                  "author": "LL92",
                  "responsable": "staff_member_one",
                  "issueType": "broken streetlight",
                  "description": "Lampadaire mort",
                  "tags":  
                    [
                      {
                        "id": "abc",
                        "keyword": "new tag"
                      }
                    ],
                  "status" : "resolved",
                  "latitude": "46.7833",
                  "longitude": "6.65",
                  "createdOn": "2015/02/15",
                  "updateOn" : "2015/02/25"
                }
    delete:
      description: Delete a tag
      body:
        application/json:
          example: |
            {
              "tagId": "abc",
              "keyword": "new tag"
            }
      responses:
        201:
          body:
            application/json:
              example: |
                {
                  "id": "123",
                  "author": "LL92",
                  "responsable": "staff_member_one",
                  "issueType": "broken streetlight",
                  "description": "Lampadaire mort",
                  "tags":  
                    [
                      {
                        "id": "abc",
                        "keyword": ""
                      }
                    ],
                  "status" : "resolved",
                  "latitude": "46.7833",
                  "longitude": "6.65",
                  "createdOn": "2015/02/15",
                  "updateOn" : "2015/02/25"
                }